// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEpV4AOpbMRE8KlJdYv6UmcuNkPobjiHg',
    appId: '1:861601972069:web:3d123cb70df523f0bc6b8c',
    messagingSenderId: '861601972069',
    projectId: 'delivery-platform-atbara',
    authDomain: 'delivery-platform-atbara.firebaseapp.com',
    storageBucket: 'delivery-platform-atbara.firebasestorage.app',
    measurementId: 'G-ELRKH8D5E2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW11bNF8gtN-y-fP50-7betQZBhZmNuHY',
    appId: '1:861601972069:android:0582426197f3a344bc6b8c',
    messagingSenderId: '861601972069',
    projectId: 'delivery-platform-atbara',
    storageBucket: 'delivery-platform-atbara.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUbIGNDBxX6tm4mtPUz-VjXrSHYmcMQeE',
    appId: '1:861601972069:ios:0e3e65691a9fbc67bc6b8c',
    messagingSenderId: '861601972069',
    projectId: 'delivery-platform-atbara',
    storageBucket: 'delivery-platform-atbara.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUbIGNDBxX6tm4mtPUz-VjXrSHYmcMQeE',
    appId: '1:861601972069:ios:0e3e65691a9fbc67bc6b8c',
    messagingSenderId: '861601972069',
    projectId: 'delivery-platform-atbara',
    storageBucket: 'delivery-platform-atbara.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEpV4AOpbMRE8KlJdYv6UmcuNkPobjiHg',
    appId: '1:861601972069:web:e0a585cd40ec7320bc6b8c',
    messagingSenderId: '861601972069',
    projectId: 'delivery-platform-atbara',
    authDomain: 'delivery-platform-atbara.firebaseapp.com',
    storageBucket: 'delivery-platform-atbara.firebasestorage.app',
    measurementId: 'G-B6FPXETTSR',
  );
}
